#ifndef PICKING_GLSL
#define PICKING_GLSL

#define PICKING_POSITION_ATTRIB_LOCATION 0

#define PICKING_MVP_UNIFORM_LOCATION 0
#define PICKING_INSTANCEID_UNIFORM_LOCATION 1

#define PICKING_COLOR_ATTACHMENT 0

#endif // PICKING_GLSL